### PR TITLE
COMMONS-505 User Notification Page are not accessible

### PR DESCRIPTION
**Pull request by boubaker**
Sort the lists in "setter" instead of sorting them in "getter" to avoid a ConcurrentModificationException

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
Your description does not seem to match with the PR content.
Can you explain the root cause of this issue ?

**Comment by boubaker** [comment]
> Your description does not seem to match with the PR content.
Can you explain the root cause of this issue ?

That's true, I have changed it.

**Comment by thomasdelhomenie** [comment]
Thanks.
Do you know why we have this issue now ? I just want to be sure it does not hide anything else...

**Comment by boubaker** [comment]
This is similar to this : 
http://stackoverflow.com/questions/32718852/concurrentmodificationexception-only-in-java-1-8-0-45
Even if the list is sorted when the sort is applied again, the list is marked as modified.
So if we make a sort inside "getPlugins", even if it hasn't changed, it will throw a ConcurrentModificationException. But, if we add the sort on "setter" instead, we will not face such a problem.

**Comment by thomasdelhomenie** [comment]
I understand the code change, but I am wondering why we this issue occurs now.
On the tribe it didn't seem to happen few weeks ago, did we change the JDK version on the tribe ?
For the product, is this issue only happens with some JDK 8 versions and not with others ? Or did you change something in the product which causes this issue ?

**Comment by boubaker** [comment]
In fact, it's a combinaison between two things:
- The sort algorithm that changed in Java 8
- The plugins are considered in sort operation: https://github.com/exodev/commons/commit/eca3c43c737bcecde7bc38fe400d31f026f988be

**Comment by thomasdelhomenie** [comment]
ok, it is clear now! Thanks.

**Comment by boubaker** [comment]
Merged

**Pull request closed without merging**
