### PR TITLE
Feature/upgrade ckeditor

### PR DESCRIPTION
**Pull request by alaameddeb**

### CODE REVIEW

**Comment by boubaker** [comment]
Discussion copied from #135 (@thomasdelhomenie)

> @alaameddeb it seems most of the translations files of the plugins have been removed, right ? why ?

**Comment by alaameddeb** [comment]
@thomasdelhomenie 
I added the new version of CKEditor full version with its default plugins and used extra plugins with its latest versions and removed unused plugins not only translations

**Comment by thomasdelhomenie** [comment]
ok
I think the initial goal of having all these (unused) plugins in the product was to allow the customers to easily use these plugins by simply updating the ckeditor configuration. I am ok for removing these plugins if we have an easy way for customers to add these plugins. Can you check that please ?

**Comment by alaameddeb** [comment]
To add a plugin it must be added in the plugins folder of ckeditor then updating the configuration file.

**Comment by alaameddeb** [comment]
@thomasdelhomenie I will re-add these plugins with its latest versions

**Comment by thomasdelhomenie** [comment]
Yes, customers cannot alter the eXo webapps (at least it is not the recommended approach), so it must be done from an extension.
I am not 100% sure it is easibly feasible to add a plugin from an extension, but I think it is. We have to be sure of that if we want to remove all these plugins.

**Comment by alaameddeb** [comment]
@thomasdelhomenie 
I added plugins in its latest versions, can you check?

**Comment by alaameddeb** [comment]
@thomasdelhomenie can you validate?

**Pull request merged**
