### PR TITLE
COMMONS-405 add removing XSS content function

### PR DESCRIPTION
**Pull request by vudangngoc**

### CODE REVIEW

**Comment by exo-swf** [comment]
Can one of the admins verify this patch?

**Comment by thomasdelhomenie** [comment]
OK to test.

**Comment by exo-swf** [comment]
Can one of the admins verify this patch?

**Comment by boubaker** [comment]
IMO, we should use the same Sanitizer as :
https://jira.exoplatform.org/browse/COMMONS-487

**Pull request closed without merging**
