### PR TITLE
PLF-8064 : make sure the migrations do not fail when no node to migrate

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
With the minimal profile enabled, the list of nodes to migrate is null, which makes fail the migration.
The fix ensures it will not fail in this case.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
This fix is about fixing PLF-8064, so to be sure it starts successfully. Customers do not use intranet default site with minimal, since it does not make sense (as shown in your screenshot).

IMO we should open another issue to fix all the issues related to minimal profile and make sure only the needed services are enabled. It will require a lot of tests. Is that ok for you ?

**Comment by thomasdelhomenie** [comment]
When I disable the portlet platformNavigation/NotificationPopoverToolbarPortlet in the ModuleRegistry, the script is still loaded and the error still appears.
As discussed, fixing these issues and enabling only the minimal components will take time and it requires a spec. Moreover customers using the minimal profile do not use the intranet site, nor the default sharelayout.

**Comment by boubaker** [comment]
> it requires a spec

See https://jira.exoplatform.org/browse/PLF-98

**Comment by boubaker** [comment]
ok, let's create a dedicated issue for those issues to fix Extra Services Configuration and the UI. Knowing those current modifications are sufficient for the customers for now, it's ok for me for the PRs

**Comment by thomasdelhomenie** [comment]
> ok, let's create a dedicated issue for those issues to fix Extra Services Configuration and the UI

https://jira.exoplatform.org/browse/PLF-8091

**Pull request merged**
