### PR TITLE
COMMONS-486 : merge CommonsResources.war to commons-extension.war

### PR DESCRIPTION
**Pull request by thomasdelhomenie**
Merge CommonsResources.war to commons-extension.war

### CODE REVIEW

**Comment by wkhessairi** [comment]
The following js files are missing in the path "commons-extension-webapp/src/main/webapp/ckeditor/plugins/basicstyles/lang/":
ro.js 
ru.js 
si.js 
sk.js 
sl.js 
sq.js 
sr-latn.js 
sr.js 
sv.js 
th.js 
tr.js 
tt.js 
ug.js 
uk.js 
vi.js 
zh-cn.js 
zh.js

**Comment by wkhessairi** [comment]
"CommonsResources" should be replaced in the following files:
- https://github.com/exodev/commons/blob/develop/commons-webui-resources/src/main/webapp/eXoPlugins/insertGadget/plugin.js#L24

- https://github.com/exodev/commons/blob/develop/commons-webui-resources/src/main/webapp/eXoPlugins/insertPortalLink/insertPortalLink.html#L30

- https://github.com/exodev/commons/blob/develop/commons-webui-resources/src/main/webapp/eXoPlugins/insertGadget/gadget.html#L27

- https://github.com/exodev/commons/blob/a48feb9331b01e9ac4eab402d39064ce1e1f3152/commons-webui-resources/src/main/webapp/eXoConfig.js#L9-10

- https://github.com/exodev/commons/blob/4e0994784117c154ba08b1fd83567a309e647463/commons-webui-resources/src/main/webapp/eXoPlugins/insertPortalLink/js/portalLink.js#L136

**Comment by thomasdelhomenie** [comment]
> https://github.com/exodev/commons/blob/develop/commons-webui-resources/src/main/webapp/eXoPlugins/insertGadget/plugin.js#L24
> https://github.com/exodev/commons/blob/develop/commons-webui-resources/src/main/webapp/eXoPlugins/insertPortalLink/insertPortalLink.html#L30
> https://github.com/exodev/commons/blob/develop/commons-webui-resources/src/main/webapp/eXoPlugins/insertGadget/gadget.html#L27

The module commons-webui-resources does not exist anymore. You are pointing on files on the develop branch.

> https://github.com/exodev/commons/blob/a48feb9331b01e9ac4eab402d39064ce1e1f3152/commons-webui-resources/src/main/webapp/eXoConfig.js#L9-10
> https://github.com/exodev/commons/blob/4e0994784117c154ba08b1fd83567a309e647463/commons-webui-resources/src/main/webapp/eXoPlugins/insertPortalLink/js/portalLink.js#L136

You are referring to develop commit also, not to this PR commit. For example, for eXoConfig.js file, the version related to this PR is : https://github.com/exodev/commons/blob/fix/COMMONS-486/commons-extension-webapp/src/main/webapp/eXoConfig.js

**Comment by thomasdelhomenie** [comment]
About missing lang files, I can see them in https://github.com/exodev/commons/tree/fix/COMMONS-486/commons-extension-webapp/src/main/webapp/ckeditor/plugins/basicstyles/lang

**Comment by wkhessairi** [comment]
yes right, I used the wrong references.
LGTM.

**Pull request merged**
