### PR TITLE
WIKI-1286 : Spaces are not displayed in the list of space switcher op…

### PR DESCRIPTION
**Pull request by aboughzela**
After Apply performance Improvement : https://github.com/exodev/social/pull/102/files
limit=0 return no data (fonctionnel regression on end point /rest/private/portal/social/spaces/lastVisitedSpace/list.json)
As solution set a default limit as 50 
You should add load more action to load more than 50 spaces.

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
Don't we have the same behavior as previously if we use limit=-1 ?

**Comment by thomasdelhomenie** [comment]
Actually, limiting the number of spaces seems to be a good thing since displaying a lot of spaces does not fit well in the UI. I think we should even lower the limit, maybe to 10.

**Comment by aboughzela** [comment]
Is not too limiting to display only 10, I will try to verify the max number of spaces can Display without broken the actual UI

**Comment by aboughzela** [comment]
We can limit the number to 20 (use case tested):
* No UI broken
* It will not cause performance problem
WYDT ?

**Comment by thomasdelhomenie** [comment]
We must wait for @hghorbel opinion for that. I already mentioned him in the jira issue.

**Comment by aboughzela** [comment]
PR updated

**Pull request closed without merging**
