### PR TITLE
PLF-6913 URL link should be opened in a new tab

### PR DESCRIPTION
**Pull request by nttuyen**
- Add attr target="_blank" when insert link in composer
- Allow attribute target on a tag in HtmlSanitizer

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
It means that:
* previous activities have still link opening in the same tab
* the target is added only through the activity composer in the UI, but not through the API for example

Couldn't we automatically add a target attribute on all link at rendering time instead ? It would solve both issues.

**Comment by nttuyen** [comment]
Now, for the old post we are already trying to detect link and insert a tag to make it clickable and we insert the target = "_blank" also but it's discarded in HtmlSanitizer.
Therefore, after apply this PR, the detected link in activity will be opened in new tab too.

I don't think we should do add target = "_blank" after we do HtmlSanitizer (and other HTML filter) when display an activity.

**Comment by thomasdelhomenie** [comment]
If I understand well, allowing "target" in the HTMLSanitizer should be sufficient to make the link open in a new tab (since you say we already do the change at rendering time), right ?

**Comment by nttuyen** [comment]
It's sufficient only for the case the link is detected automatically (mean user type a valid url in composer like http://google.com then we will auto wrap it into an "a" tag). 
But for the link already in "a" tag like when user inserts via insertLink dialog in microblog composer, we have to add target="_blank" when create link tag. If not it still opens in current tab.

**Comment by thomasdelhomenie** [comment]
So it seems to be the right solution, adding blank target on existing link tag, no ?

**Comment by nttuyen** [comment]
No, I did not add target into existing link tag and I think we should not do that as let the link tag works as user want when insert it.

**Comment by thomasdelhomenie** [comment]
The user does not have the choice, he cannot select the target value, so we can always force to open it in a new tab by adding a blank target IMO.

**Comment by nttuyen** [comment]
Now, when user insert the link via the insertLink dialog we will auto insert the target="_blank" in javascript. If he type the link directly in composer, we will force that link open in new tab by insert target="_blank" also. 
So, in the user side, the inserted link always to open in new tab.

The link tag without target="_blank" is inserted in programmatically only like in the forum, wiki we want to add link when create activity for wiki, topic,...

**Comment by thomasdelhomenie** [comment]
This does not cover the case where links are inserted programmatically by third-parties. Let's imagine a Jira integration which pushes an activity through the API with a link to a Jira issue. We should always make sure this link opens in a new tab as well.
Also, the issue does not mention that wiki, forum, ... links should be opened in the same tab.

**Comment by nttuyen** [comment]
So, you mean we will force every link in activity have to be opened in new tab? include the link to wiki, forum,...?
I will update PR to do that. But maybe we still need update to allow it in HTMLSanitizer

**Comment by nttuyen** [comment]
@thomasdelhomenie [PR 133|https://github.com/exodev/social/pull/133] is updated with introduce the filter to force all link in activity open in new tab. Could you please review it again. 
I will close this PR as we don't need it any more.

**Pull request closed without merging**
